test_user_detection_false (T3_US01.US01) ... ok
test_user_detection_true (T3_US01.US01) ... ok
test_turn_light_off_occupancy (T3_US02.US02) ... ok
test_turn_light_on_occupancy (T3_US02.US02) ... ok
test_light_off_no_user (T3_US03.US03) ... ok
test_light_off_user (T3_US03.US03) ... ok
test_temperature_reading (T3_US04.US04) ... ok
test_window_closed_temperature_in_range (T3_US04.US04) ... ERROR
test_window_closed_temperature_out_of_range (T3_US04.US04) ... ERROR
test_window_open_temperature_in_range (T3_US04.US04) ... ERROR
test_buzzer_off_gas_detected (T3_US05.US05) ... ok
test_buzzer_on_gas_detected (T3_US05.US05) ... ok

======================================================================
ERROR: test_window_closed_temperature_in_range (T3_US04.US04)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Michelangelo\AppData\Local\Programs\Python\Python310\lib\unittest\mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "C:\Users\Michelangelo\CS\Python\tasks_analysis\test\T3_US04.py", line 29, in test_window_closed_temperature_in_range
    self.sh.manage_window()
  File "C:\Users\Michelangelo\CS\Python\tasks_analysis\SmartHome.py", line 136, in manage_window
    raise error
  File "C:\Users\Michelangelo\CS\Python\tasks_analysis\SmartHome.py", line 118, in manage_window
    if 18 < self.dht_indoor <30 and 18 < self.dht_outdoor < 30:
TypeError: '<' not supported between instances of 'int' and 'DHT11'

======================================================================
ERROR: test_window_closed_temperature_out_of_range (T3_US04.US04)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Michelangelo\AppData\Local\Programs\Python\Python310\lib\unittest\mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "C:\Users\Michelangelo\CS\Python\tasks_analysis\test\T3_US04.py", line 22, in test_window_closed_temperature_out_of_range
    self.sh.manage_window()
  File "C:\Users\Michelangelo\CS\Python\tasks_analysis\SmartHome.py", line 136, in manage_window
    raise error
  File "C:\Users\Michelangelo\CS\Python\tasks_analysis\SmartHome.py", line 118, in manage_window
    if 18 < self.dht_indoor <30 and 18 < self.dht_outdoor < 30:
TypeError: '<' not supported between instances of 'int' and 'DHT11'

======================================================================
ERROR: test_window_open_temperature_in_range (T3_US04.US04)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Michelangelo\AppData\Local\Programs\Python\Python310\lib\unittest\mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "C:\Users\Michelangelo\CS\Python\tasks_analysis\test\T3_US04.py", line 36, in test_window_open_temperature_in_range
    self.sh.manage_window()
  File "C:\Users\Michelangelo\CS\Python\tasks_analysis\SmartHome.py", line 136, in manage_window
    raise error
  File "C:\Users\Michelangelo\CS\Python\tasks_analysis\SmartHome.py", line 118, in manage_window
    if 18 < self.dht_indoor <30 and 18 < self.dht_outdoor < 30:
TypeError: '<' not supported between instances of 'int' and 'DHT11'

----------------------------------------------------------------------
Ran 12 tests in 36.206s

FAILED (errors=3)
